
import streamlit as st  
from dotenv import load_dotenv
import os  
from diffusers import StableDiffusionPipeline
import torch

load_dotenv()


def generate_images_using_huggingface_diffusers(text):
    pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float32)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    pipe = pipe.to(device)
    prompt = text
    image = pipe(prompt).images[0]  
    return image


choice = st.sidebar.selectbox("Select your choice", ["Home", "Huggingface Diffusers"])

if choice == "Home":
    st.title("PromptArt AI")
    with st.expander("About the App"):
        st.write("This is a simple image generation app that generates images from a text prompt using Hugging Face's Stable Diffusion.")

elif choice == "Huggingface Diffusers":
    st.subheader("Image generation using Huggingface Diffusers")
    input_prompt = st.text_input("Enter your text prompt")
    if input_prompt:
        if st.button("Generate Image"):
            image_output = generate_images_using_huggingface_diffusers(input_prompt)
            st.info("Generating image.....")
            st.success("Image Generated Successfully")
            st.image(image_output, caption="Generated by Huggingface Diffusers")
